scimaf_dir --db twi_neo_nightpattern1v2.1_10yrs.db
scimaf_dir --db twi_neo_nightpattern2v2.1_10yrs.db
scimaf_dir --db twi_neo_nightpattern3v2.1_10yrs.db
scimaf_dir --db twi_neo_nightpattern4v2.1_10yrs.db
scimaf_dir --db twi_neo_nightpattern5v2.1_10yrs.db
scimaf_dir --db twi_neo_nightpattern6v2.1_10yrs.db
scimaf_dir --db twi_neo_nightpattern7v2.1_10yrs.db
glance_dir --db twi_neo_nightpattern1v2.1_10yrs.db
glance_dir --db twi_neo_nightpattern2v2.1_10yrs.db
glance_dir --db twi_neo_nightpattern3v2.1_10yrs.db
glance_dir --db twi_neo_nightpattern4v2.1_10yrs.db
glance_dir --db twi_neo_nightpattern5v2.1_10yrs.db
glance_dir --db twi_neo_nightpattern6v2.1_10yrs.db
glance_dir --db twi_neo_nightpattern7v2.1_10yrs.db