python shave.py --exptime 40
python shave.py --exptime 38
python shave.py --exptime 35
python shave.py --exptime 32
python shave.py --exptime 30
python shave.py --exptime 28
python shave.py --exptime 25
python shave.py --exptime 22
python shave.py --exptime 20
