python ddf_dither_size.py --maxDither .01
python ddf_dither_size.py --maxDither .05
python ddf_dither_size.py --maxDither .1
python ddf_dither_size.py --maxDither .25
python ddf_dither_size.py --maxDither .5
python ddf_dither_size.py --maxDither .7
python ddf_dither_size.py --maxDither 1.0
python ddf_dither_size.py --maxDither 1.5
python ddf_dither_size.py --maxDither 2.5
python ddf_dither_size.py --maxDither 3.5
